[package]
name = "jungle-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.14", features = ["tokio"] }
iced-sugiyama = { path = "../../iced-sugiyama" }
jungle-client = { path = "../jungle-client" }
jungle-types = { path = "../jungle-types" }
image = { version = "0.25", default-features = false, features = ["png"] }
uuid = { workspace = true }

[lints]
workspace = true
