[package]
name = "jungle-migrate"
version = "0.1.0"
edition = "2021"

[features]
default = []
postgres = ["dep:sqlx"]
fjall = ["dep:fjall"]

[dependencies]
tracing = "0.1"
sqlx = { version = "0.8", optional = true, features = ["postgres", "runtime-tokio-rustls"] }
fjall = { workspace = true, optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
testcontainers = "0.23"
testcontainers-modules = { version = "0.11", features = ["postgres"] }

[lints]
workspace = true
