[workspace]
resolver = "2"
members = [
    "jungle-core",
    "jungle-cli",
    "jungle-server",
    "jungle-sdk",
    "jungle-persist",
    "jungle-test",
    "jungle-viewer",
    "jungle-proto",
    "jungle-types",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
inception = { path = "../inception/inception" }
typosaurus = { path = "../typosaurus" }
