[workspace]
resolver = "2"
members = [
    "jungle-core",
    "jungle-cli",
    "jungle-client",
    "jungle-macros",
    "jungle-server",
    "jungle-sdk",
    "jungle-persist",
    "jungle-test",
    "jungle-viewer",
    "jungle-types",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
postcard = "1.1"
inception = { path = "../inception/inception" }
typosaurus = { path = "../typosaurus" }
futures = "0.3"
uuid = { version = "1", features = ["serde"] }
async-trait = "0.1"
dyn-clone = "1"
