[package]
name = "jungle-zoo"
version = "0.1.0"
edition = "2021"

[features]
default = []
delay = ["dep:tokio"]

[dependencies]
serde = { workspace = true }
jungle-types = { path = "../jungle-types" }
jungle_sdk = { package = "jungle-sdk", path = "../jungle-sdk" }
tokio = { version = "1", features = ["time"], optional = true }
