[package]
name = "jungle-core"
version = "0.1.0"
edition = "2021"

[dependencies]
jungle-client = { path = "../jungle-client" }
jungle-types = { path = "../jungle-types" }
typosaurus = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
postcard = { workspace = true }
tokio = { version = "1", features = ["time"] }
