/// An inhabitant of the Jungle.
pub trait Entity {
    /// The result of observing this `Entity`
    type Appearance;

    /// What is required to drive this `Entity`
    type Motive;

    /// The fundamental behavior of this `Entity`.
    type Instinct;
}

/// An active member of the current Jungle ecosystem.
pub trait Animal: Entity {
    fn observe(&self) -> Self::Appearance;
    fn drive(&self, motive: Self::Motive);
}

/// An internal motivation or drive to act.
pub trait Impulse {
    // TODO: flesh out as needed
}

/// A basic action implementing `Impulse`.
pub struct Action;
impl Impulse for Action {}

/// Grouping for `Species`
// TODO: this should be user-space-generated by decmac
pub enum Genus {}

/// Grouping for `Animal`
// TODO: this should be user-space generated by decmac
pub enum Species {}
