/// Taxonomic traits for Jungle entities.
///
/// These traits define the grouping hierarchy used to organize
/// species and animals within the ecosystem.

/// Grouping for `Species`
// TODO: this should be user-space-generated by decmac
pub trait Genus {}

/// Grouping for `Animal`
// TODO: this should be user-space generated by decmac
pub trait Species {}
