[package]
name = "jungle-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
postcard = { workspace = true, features = ["alloc"] }
inception = { workspace = true }
typosaurus = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["time", "rt-multi-thread", "macros"] }

[lints]
workspace = true

