use std::time::Duration;

use super::{GridNote, Kind, Position};
use crate::instrumentation::{LeadGuitarArticulation, Note};

const INTRO: &[GridNote] = &[
    GridNote {
        midi: 57,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 14.634146,
        position: Position {
            bar: 8,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 20.487805,
        position: Position {
            bar: 11,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 21.463415,
        position: Position {
            bar: 12,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 22.439024,
        position: Position {
            bar: 12,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 26.341463,
        position: Position {
            bar: 14,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const VERSE1: &[GridNote] = &[
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 34.146341,
        position: Position {
            bar: 18,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 41.95122,
        position: Position {
            bar: 22,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 49.756098,
        position: Position {
            bar: 26,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 51.707317,
        position: Position {
            bar: 27,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 53.658537,
        position: Position {
            bar: 28,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const CHORUS1: &[GridNote] = &[
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 59.512195,
        position: Position {
            bar: 31,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 59.878049,
        position: Position {
            bar: 31,
            beat: 3,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 60.243902,
        position: Position {
            bar: 31,
            beat: 4,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 61.463415,
        position: Position {
            bar: 32,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const VERSE2: &[GridNote] = &[
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 69.268293,
        position: Position {
            bar: 36,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 77.073171,
        position: Position {
            bar: 40,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 79.02439,
        position: Position {
            bar: 41,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 80.97561,
        position: Position {
            bar: 42,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const CHORUS2: &[GridNote] = &[
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 86.829268,
        position: Position {
            bar: 45,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 87.195122,
        position: Position {
            bar: 45,
            beat: 3,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 87.560976,
        position: Position {
            bar: 45,
            beat: 4,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 88.780488,
        position: Position {
            bar: 46,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const SOLO1: &[GridNote] = &[GridNote {
    midi: 57,
    kind: Kind::Eighth,
    beats: 0.5,
    d_sec: 0.243902,
    t_sec: 104.390244,
    position: Position {
        bar: 54,
        beat: 3,
        beat_offset_num: 0,
        beat_offset_den: 1,
    },
}];

const VERSE3: &[GridNote] = &[
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 112.195122,
        position: Position {
            bar: 58,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 120.0,
        position: Position {
            bar: 62,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 121.95122,
        position: Position {
            bar: 63,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 123.902439,
        position: Position {
            bar: 64,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const CHORUS3: &[GridNote] = &[
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 129.756098,
        position: Position {
            bar: 67,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 130.121951,
        position: Position {
            bar: 67,
            beat: 3,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 130.487805,
        position: Position {
            bar: 67,
            beat: 4,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 131.707317,
        position: Position {
            bar: 68,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const BRIDGE1: &[GridNote] = &[GridNote {
    midi: 57,
    kind: Kind::Eighth,
    beats: 0.5,
    d_sec: 0.243902,
    t_sec: 153.170732,
    position: Position {
        bar: 79,
        beat: 3,
        beat_offset_num: 0,
        beat_offset_den: 1,
    },
}];

const SOLO2: &[GridNote] = &[
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 160.97561,
        position: Position {
            bar: 83,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 162.682927,
        position: Position {
            bar: 84,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 164.878049,
        position: Position {
            bar: 85,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 166.585366,
        position: Position {
            bar: 86,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 170.487805,
        position: Position {
            bar: 88,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 172.012195,
        position: Position {
            bar: 89,
            beat: 1,
            beat_offset_num: 5,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 172.256098,
        position: Position {
            bar: 89,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 172.5,
        position: Position {
            bar: 89,
            beat: 2,
            beat_offset_num: 5,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 173.170732,
        position: Position {
            bar: 89,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 174.146341,
        position: Position {
            bar: 90,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 175.121951,
        position: Position {
            bar: 90,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 175.853659,
        position: Position {
            bar: 91,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 176.585366,
        position: Position {
            bar: 91,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 180.243902,
        position: Position {
            bar: 93,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 184.146341,
        position: Position {
            bar: 95,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 192.195122,
        position: Position {
            bar: 99,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 192.195122,
        position: Position {
            bar: 99,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 196.097561,
        position: Position {
            bar: 101,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 196.097561,
        position: Position {
            bar: 101,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const BRIDGE2: &[GridNote] = &[
    GridNote {
        midi: 57,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 219.512195,
        position: Position {
            bar: 113,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 220.0,
        position: Position {
            bar: 113,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 220.487805,
        position: Position {
            bar: 114,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 220.97561,
        position: Position {
            bar: 114,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 221.463415,
        position: Position {
            bar: 114,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 221.95122,
        position: Position {
            bar: 114,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 222.439024,
        position: Position {
            bar: 115,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 223.414634,
        position: Position {
            bar: 115,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 225.365854,
        position: Position {
            bar: 116,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 227.317073,
        position: Position {
            bar: 117,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const FINALE: &[GridNote] = &[
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 231.219512,
        position: Position {
            bar: 119,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 233.170732,
        position: Position {
            bar: 120,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 235.121951,
        position: Position {
            bar: 121,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 239.02439,
        position: Position {
            bar: 123,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 240.97561,
        position: Position {
            bar: 124,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 242.926829,
        position: Position {
            bar: 125,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 246.829268,
        position: Position {
            bar: 127,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 248.780488,
        position: Position {
            bar: 128,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 250.731707,
        position: Position {
            bar: 129,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 251.097561,
        position: Position {
            bar: 129,
            beat: 3,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 251.463415,
        position: Position {
            bar: 129,
            beat: 4,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 251.829268,
        position: Position {
            bar: 130,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 252.195122,
        position: Position {
            bar: 130,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 252.439024,
        position: Position {
            bar: 130,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 252.682927,
        position: Position {
            bar: 130,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 253.04878,
        position: Position {
            bar: 130,
            beat: 3,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 253.414634,
        position: Position {
            bar: 130,
            beat: 4,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 49,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 254.146341,
        position: Position {
            bar: 131,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 57,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 254.146341,
        position: Position {
            bar: 131,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const SECTIONS: [&[GridNote]; 12] = [
    INTRO, VERSE1, CHORUS1, VERSE2, CHORUS2, SOLO1, VERSE3, CHORUS3, BRIDGE1, SOLO2, BRIDGE2,
    FINALE,
];

pub fn crash_cymbal_score() -> Vec<Note<LeadGuitarArticulation>> {
    SECTIONS
        .into_iter()
        .flatten()
        .copied()
        .map(grid_note_to_note)
        .collect()
}

fn grid_note_to_note(note: GridNote) -> Note<LeadGuitarArticulation> {
    Note {
        n_midi: note.midi,
        duration: Duration::from_secs_f32(note.d_sec),
        velocity: 37.0 / 127.0,
        amplitude_multiplier: 0.5,
        expression: None,
        offset: Duration::from_secs_f32(note.t_sec),
        articulation: LeadGuitarArticulation::Sustained,
    }
}
