use super::{collect_score_from_sections, GridNote, Kind, Position, ScheduledNote};
use crate::instrumentation::ElectricGuitarArticulation;

const INTRO: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 22.439024,
        position: Position {
            bar: 12,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 22.682927,
        position: Position {
            bar: 12,
            beat: 3,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 22.926829,
        position: Position {
            bar: 12,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 23.170732,
        position: Position {
            bar: 12,
            beat: 4,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 23.414634,
        position: Position {
            bar: 13,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 23.658537,
        position: Position {
            bar: 13,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 23.902439,
        position: Position {
            bar: 13,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 24.146341,
        position: Position {
            bar: 13,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 24.390244,
        position: Position {
            bar: 13,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 24.634146,
        position: Position {
            bar: 13,
            beat: 3,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 24.878049,
        position: Position {
            bar: 13,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 25.121951,
        position: Position {
            bar: 13,
            beat: 4,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 25.365854,
        position: Position {
            bar: 14,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 25.426829,
        position: Position {
            bar: 14,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 25.914634,
        position: Position {
            bar: 14,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 25.97561,
        position: Position {
            bar: 14,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 26.829268,
        position: Position {
            bar: 14,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 27.804878,
        position: Position {
            bar: 15,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 28.780488,
        position: Position {
            bar: 15,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 29.756098,
        position: Position {
            bar: 16,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 30.731707,
        position: Position {
            bar: 16,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 31.707317,
        position: Position {
            bar: 17,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const VERSE1: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 32.682927,
        position: Position {
            bar: 17,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 33.658537,
        position: Position {
            bar: 18,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 33.902439,
        position: Position {
            bar: 18,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 34.02439,
        position: Position {
            bar: 18,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 34.634146,
        position: Position {
            bar: 18,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 35.609756,
        position: Position {
            bar: 19,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 36.585366,
        position: Position {
            bar: 19,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 37.560976,
        position: Position {
            bar: 20,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 38.536585,
        position: Position {
            bar: 20,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 39.512195,
        position: Position {
            bar: 21,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 40.487805,
        position: Position {
            bar: 21,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 41.463415,
        position: Position {
            bar: 22,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 41.707317,
        position: Position {
            bar: 22,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 41.829268,
        position: Position {
            bar: 22,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 42.439024,
        position: Position {
            bar: 22,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 43.414634,
        position: Position {
            bar: 23,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 44.390244,
        position: Position {
            bar: 23,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 45.365854,
        position: Position {
            bar: 24,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 46.341463,
        position: Position {
            bar: 24,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 47.317073,
        position: Position {
            bar: 25,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 48.292683,
        position: Position {
            bar: 25,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 49.268293,
        position: Position {
            bar: 26,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 49.329268,
        position: Position {
            bar: 26,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 50.243902,
        position: Position {
            bar: 26,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 51.219512,
        position: Position {
            bar: 27,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 52.195122,
        position: Position {
            bar: 27,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 53.170732,
        position: Position {
            bar: 28,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 53.231707,
        position: Position {
            bar: 28,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 53.47561,
        position: Position {
            bar: 28,
            beat: 2,
            beat_offset_num: 5,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 53.536585,
        position: Position {
            bar: 28,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 54.146341,
        position: Position {
            bar: 28,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const CHORUS1: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 55.121951,
        position: Position {
            bar: 29,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 56.097561,
        position: Position {
            bar: 29,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 57.073171,
        position: Position {
            bar: 30,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 58.04878,
        position: Position {
            bar: 30,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 59.02439,
        position: Position {
            bar: 31,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 60.97561,
        position: Position {
            bar: 32,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 61.036585,
        position: Position {
            bar: 32,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 61.95122,
        position: Position {
            bar: 32,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 62.926829,
        position: Position {
            bar: 33,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 63.902439,
        position: Position {
            bar: 33,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 64.878049,
        position: Position {
            bar: 34,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 65.853659,
        position: Position {
            bar: 34,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 66.829268,
        position: Position {
            bar: 35,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const VERSE2: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 67.804878,
        position: Position {
            bar: 35,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 68.780488,
        position: Position {
            bar: 36,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 69.02439,
        position: Position {
            bar: 36,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 69.146341,
        position: Position {
            bar: 36,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 69.756098,
        position: Position {
            bar: 36,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 70.731707,
        position: Position {
            bar: 37,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 71.707317,
        position: Position {
            bar: 37,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 72.682927,
        position: Position {
            bar: 38,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 73.658537,
        position: Position {
            bar: 38,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 74.634146,
        position: Position {
            bar: 39,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 75.609756,
        position: Position {
            bar: 39,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 76.585366,
        position: Position {
            bar: 40,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 76.646341,
        position: Position {
            bar: 40,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 77.560976,
        position: Position {
            bar: 40,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 78.536585,
        position: Position {
            bar: 41,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 79.512195,
        position: Position {
            bar: 41,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 80.487805,
        position: Position {
            bar: 42,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 80.54878,
        position: Position {
            bar: 42,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 80.792683,
        position: Position {
            bar: 42,
            beat: 2,
            beat_offset_num: 5,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 80.853659,
        position: Position {
            bar: 42,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 81.463415,
        position: Position {
            bar: 42,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const CHORUS2: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 82.439024,
        position: Position {
            bar: 43,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 83.414634,
        position: Position {
            bar: 43,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 84.390244,
        position: Position {
            bar: 44,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 85.365854,
        position: Position {
            bar: 44,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 86.341463,
        position: Position {
            bar: 45,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 88.292683,
        position: Position {
            bar: 46,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 88.353659,
        position: Position {
            bar: 46,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 89.268293,
        position: Position {
            bar: 46,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 90.243902,
        position: Position {
            bar: 47,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 91.219512,
        position: Position {
            bar: 47,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 92.195122,
        position: Position {
            bar: 48,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 93.170732,
        position: Position {
            bar: 48,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const SOLO1: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 94.146341,
        position: Position {
            bar: 49,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 95.121951,
        position: Position {
            bar: 49,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 96.097561,
        position: Position {
            bar: 50,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 97.073171,
        position: Position {
            bar: 50,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 98.04878,
        position: Position {
            bar: 51,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 99.02439,
        position: Position {
            bar: 51,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 100.0,
        position: Position {
            bar: 52,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 100.97561,
        position: Position {
            bar: 52,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 101.95122,
        position: Position {
            bar: 53,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 102.926829,
        position: Position {
            bar: 53,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 103.902439,
        position: Position {
            bar: 54,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 104.146341,
        position: Position {
            bar: 54,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 104.268293,
        position: Position {
            bar: 54,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 104.878049,
        position: Position {
            bar: 54,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 105.853659,
        position: Position {
            bar: 55,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 106.829268,
        position: Position {
            bar: 55,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 107.804878,
        position: Position {
            bar: 56,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 108.780488,
        position: Position {
            bar: 56,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 109.756098,
        position: Position {
            bar: 57,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const VERSE3: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 110.731707,
        position: Position {
            bar: 57,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 111.707317,
        position: Position {
            bar: 58,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 111.95122,
        position: Position {
            bar: 58,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 112.073171,
        position: Position {
            bar: 58,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 112.682927,
        position: Position {
            bar: 58,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 113.658537,
        position: Position {
            bar: 59,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 114.634146,
        position: Position {
            bar: 59,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 115.609756,
        position: Position {
            bar: 60,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 116.585366,
        position: Position {
            bar: 60,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 117.560976,
        position: Position {
            bar: 61,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 118.536585,
        position: Position {
            bar: 61,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 119.512195,
        position: Position {
            bar: 62,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 119.573171,
        position: Position {
            bar: 62,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 120.487805,
        position: Position {
            bar: 62,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 121.463415,
        position: Position {
            bar: 63,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 122.439024,
        position: Position {
            bar: 63,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 123.414634,
        position: Position {
            bar: 64,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 123.47561,
        position: Position {
            bar: 64,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 123.719512,
        position: Position {
            bar: 64,
            beat: 2,
            beat_offset_num: 5,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 123.780488,
        position: Position {
            bar: 64,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 124.390244,
        position: Position {
            bar: 64,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const CHORUS3: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 125.365854,
        position: Position {
            bar: 65,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 126.341463,
        position: Position {
            bar: 65,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 127.317073,
        position: Position {
            bar: 66,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 128.292683,
        position: Position {
            bar: 66,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 129.268293,
        position: Position {
            bar: 67,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 131.219512,
        position: Position {
            bar: 68,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 131.280488,
        position: Position {
            bar: 68,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 132.195122,
        position: Position {
            bar: 68,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 133.170732,
        position: Position {
            bar: 69,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 134.146341,
        position: Position {
            bar: 69,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 135.121951,
        position: Position {
            bar: 70,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const BRIDGE1: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 136.097561,
        position: Position {
            bar: 70,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 137.073171,
        position: Position {
            bar: 71,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 138.04878,
        position: Position {
            bar: 71,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 139.02439,
        position: Position {
            bar: 72,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 140.0,
        position: Position {
            bar: 72,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 140.97561,
        position: Position {
            bar: 73,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 141.95122,
        position: Position {
            bar: 73,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 142.926829,
        position: Position {
            bar: 74,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 143.902439,
        position: Position {
            bar: 74,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 144.878049,
        position: Position {
            bar: 75,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 144.939024,
        position: Position {
            bar: 75,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 145.853659,
        position: Position {
            bar: 75,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 146.829268,
        position: Position {
            bar: 76,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 146.890244,
        position: Position {
            bar: 76,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 147.804878,
        position: Position {
            bar: 76,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 148.780488,
        position: Position {
            bar: 77,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 148.841463,
        position: Position {
            bar: 77,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 149.756098,
        position: Position {
            bar: 77,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 150.731707,
        position: Position {
            bar: 78,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 151.219512,
        position: Position {
            bar: 78,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 151.219512,
        position: Position {
            bar: 78,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 151.463415,
        position: Position {
            bar: 78,
            beat: 3,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 151.707317,
        position: Position {
            bar: 78,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 151.95122,
        position: Position {
            bar: 78,
            beat: 4,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 152.195122,
        position: Position {
            bar: 79,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 152.682927,
        position: Position {
            bar: 79,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 152.743902,
        position: Position {
            bar: 79,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 153.658537,
        position: Position {
            bar: 79,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 154.634146,
        position: Position {
            bar: 80,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 155.609756,
        position: Position {
            bar: 80,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 156.585366,
        position: Position {
            bar: 81,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 157.560976,
        position: Position {
            bar: 81,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const SOLO2: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 158.536585,
        position: Position {
            bar: 82,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 159.512195,
        position: Position {
            bar: 82,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 160.0,
        position: Position {
            bar: 83,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 160.060976,
        position: Position {
            bar: 83,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 160.54878,
        position: Position {
            bar: 83,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 160.609756,
        position: Position {
            bar: 83,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 161.463415,
        position: Position {
            bar: 83,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 162.439024,
        position: Position {
            bar: 84,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 163.414634,
        position: Position {
            bar: 84,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 164.390244,
        position: Position {
            bar: 85,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 165.365854,
        position: Position {
            bar: 85,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 166.341463,
        position: Position {
            bar: 86,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 167.317073,
        position: Position {
            bar: 86,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 168.292683,
        position: Position {
            bar: 87,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 169.268293,
        position: Position {
            bar: 87,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 170.243902,
        position: Position {
            bar: 88,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 171.219512,
        position: Position {
            bar: 88,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 171.707317,
        position: Position {
            bar: 89,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 171.768293,
        position: Position {
            bar: 89,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 173.170732,
        position: Position {
            bar: 89,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 174.146341,
        position: Position {
            bar: 90,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 175.121951,
        position: Position {
            bar: 90,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 177.073171,
        position: Position {
            bar: 91,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 178.04878,
        position: Position {
            bar: 92,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 179.02439,
        position: Position {
            bar: 92,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 180.0,
        position: Position {
            bar: 93,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 180.97561,
        position: Position {
            bar: 93,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 181.95122,
        position: Position {
            bar: 94,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 182.926829,
        position: Position {
            bar: 94,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 183.902439,
        position: Position {
            bar: 95,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 184.878049,
        position: Position {
            bar: 95,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 185.853659,
        position: Position {
            bar: 96,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 186.829268,
        position: Position {
            bar: 96,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 187.317073,
        position: Position {
            bar: 97,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Quarter,
        beats: 1.0,
        d_sec: 0.487805,
        t_sec: 187.804878,
        position: Position {
            bar: 97,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 188.292683,
        position: Position {
            bar: 97,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 188.536585,
        position: Position {
            bar: 97,
            beat: 3,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 188.780488,
        position: Position {
            bar: 97,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 189.02439,
        position: Position {
            bar: 97,
            beat: 4,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 189.268293,
        position: Position {
            bar: 98,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 189.512195,
        position: Position {
            bar: 98,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 189.756098,
        position: Position {
            bar: 98,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 190.0,
        position: Position {
            bar: 98,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 190.243902,
        position: Position {
            bar: 98,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 190.487805,
        position: Position {
            bar: 98,
            beat: 3,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 190.731707,
        position: Position {
            bar: 98,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 190.97561,
        position: Position {
            bar: 98,
            beat: 4,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 191.219512,
        position: Position {
            bar: 99,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 191.463415,
        position: Position {
            bar: 99,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 2,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 191.707317,
        position: Position {
            bar: 99,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 191.768293,
        position: Position {
            bar: 99,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
];

const BRIDGE2: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 219.02439,
        position: Position {
            bar: 113,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 219.085366,
        position: Position {
            bar: 113,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 219.329268,
        position: Position {
            bar: 113,
            beat: 2,
            beat_offset_num: 5,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 219.390244,
        position: Position {
            bar: 113,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 222.926829,
        position: Position {
            bar: 115,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 222.987805,
        position: Position {
            bar: 115,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 223.902439,
        position: Position {
            bar: 115,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 224.878049,
        position: Position {
            bar: 116,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 225.853659,
        position: Position {
            bar: 116,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 226.829268,
        position: Position {
            bar: 117,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 226.890244,
        position: Position {
            bar: 117,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 227.134146,
        position: Position {
            bar: 117,
            beat: 2,
            beat_offset_num: 5,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 227.195122,
        position: Position {
            bar: 117,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 227.804878,
        position: Position {
            bar: 117,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
];

const FINALE: &[GridNote] = &[
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 228.780488,
        position: Position {
            bar: 118,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 229.756098,
        position: Position {
            bar: 118,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 230.731707,
        position: Position {
            bar: 119,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 231.707317,
        position: Position {
            bar: 119,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 232.682927,
        position: Position {
            bar: 120,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 233.658537,
        position: Position {
            bar: 120,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 234.634146,
        position: Position {
            bar: 121,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 234.695122,
        position: Position {
            bar: 121,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 234.939024,
        position: Position {
            bar: 121,
            beat: 2,
            beat_offset_num: 5,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 235.0,
        position: Position {
            bar: 121,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 235.609756,
        position: Position {
            bar: 121,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 236.585366,
        position: Position {
            bar: 122,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 237.560976,
        position: Position {
            bar: 122,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 238.536585,
        position: Position {
            bar: 123,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 239.512195,
        position: Position {
            bar: 123,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 240.487805,
        position: Position {
            bar: 124,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 241.463415,
        position: Position {
            bar: 124,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 242.439024,
        position: Position {
            bar: 125,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 242.5,
        position: Position {
            bar: 125,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 242.743902,
        position: Position {
            bar: 125,
            beat: 2,
            beat_offset_num: 5,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 242.804878,
        position: Position {
            bar: 125,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 243.414634,
        position: Position {
            bar: 125,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 244.390244,
        position: Position {
            bar: 126,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 245.365854,
        position: Position {
            bar: 126,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 246.341463,
        position: Position {
            bar: 127,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 247.317073,
        position: Position {
            bar: 127,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 248.292683,
        position: Position {
            bar: 128,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 249.268293,
        position: Position {
            bar: 128,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 250.243902,
        position: Position {
            bar: 129,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 250.304878,
        position: Position {
            bar: 129,
            beat: 2,
            beat_offset_num: 1,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::ThirtySecond,
        beats: 0.125,
        d_sec: 0.060976,
        t_sec: 250.54878,
        position: Position {
            bar: 129,
            beat: 2,
            beat_offset_num: 5,
            beat_offset_den: 8,
        },
    },
    GridNote {
        midi: 38,
        kind: Kind::Eighth,
        beats: 0.5,
        d_sec: 0.243902,
        t_sec: 250.609756,
        position: Position {
            bar: 129,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
];

const SECTIONS: [&[GridNote]; 12] = [
    INTRO, VERSE1, CHORUS1, VERSE2, CHORUS2, SOLO1, VERSE3, CHORUS3, BRIDGE1, SOLO2, BRIDGE2,
    FINALE,
];

pub fn snare_drum_score(bpm: f32) -> Vec<ScheduledNote<ElectricGuitarArticulation>> {
    collect_score_from_sections(&SECTIONS, bpm)
}
