use std::time::Duration;

use crate::instrumentation::{LeadGuitarArticulation, Note};

const TICKS_PER_QUARTER_NOTE: u64 = 384;
const TEMPO_MICROS_PER_QUARTER_NOTE: u64 = 483_870;

#[derive(Clone, Copy)]
struct ScoreEvent {
    start_tick: u32,
    duration_tick: u32,
    n_midi: u8,
    velocity: u8,
}

const SCORE: &[ScoreEvent] = &[
    ScoreEvent {
        start_tick: 17664,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 17856,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 18048,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 18240,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 18432,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 18624,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 18816,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 19008,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 19200,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 19392,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 19584,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 19776,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 19968,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 20016,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 20400,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 20448,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 21120,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 21888,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 22656,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 23424,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 24192,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 24960,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 25728,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 26496,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 26688,
        duration_tick: 96,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 26784,
        duration_tick: 96,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 27264,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 28032,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 28800,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 29568,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 30336,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 31104,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 31872,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 32640,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 32832,
        duration_tick: 96,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 32928,
        duration_tick: 96,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 33408,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 34176,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 34944,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 35712,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 36480,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 37248,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 38016,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 38784,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 38832,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 39552,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 40320,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 41088,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 41856,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 41904,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 42096,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 42144,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 42624,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 43392,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 44160,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 44928,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 45696,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 46464,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 48000,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 48048,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 48768,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 49536,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 50304,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 51072,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 51840,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 52608,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 53376,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 54144,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 54336,
        duration_tick: 96,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 54432,
        duration_tick: 96,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 54912,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 55680,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 56448,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 57216,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 57984,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 58752,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 59520,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 60288,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 60336,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 61056,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 61824,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 62592,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 63360,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 63408,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 63600,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 63648,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 64128,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 64896,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 65664,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 66432,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 67200,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 67968,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 69504,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 69552,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 70272,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 71040,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 71808,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 72576,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 73344,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 74112,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 74880,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 75648,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 76416,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 77184,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 77952,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 78720,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 79488,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 80256,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 81024,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 81792,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 81984,
        duration_tick: 96,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 82080,
        duration_tick: 96,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 82560,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 83328,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 84096,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 84864,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 85632,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 86400,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 87168,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 87936,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 88128,
        duration_tick: 96,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 88224,
        duration_tick: 96,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 88704,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 89472,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 90240,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 91008,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 91776,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 92544,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 93312,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 94080,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 94128,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 94848,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 95616,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 96384,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 97152,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 97200,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 97392,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 97440,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 97920,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 98688,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 99456,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 100224,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 100992,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 101760,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 103296,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 103344,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 104064,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 104832,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 105600,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 106368,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 107136,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 107904,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 108672,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 109440,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 110208,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 110976,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 111744,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 112512,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 113280,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 114048,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 114096,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 114816,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 115584,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 115632,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 116352,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 117120,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 117168,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 117888,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 118656,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 119040,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 119040,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 119232,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 119424,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 119616,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 119808,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 120192,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 120240,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 120960,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 121728,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 122496,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 123264,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 124032,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 124800,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 125568,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 125952,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 126000,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 126384,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 126432,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 127104,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 127872,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 128640,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 129408,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 130176,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 130944,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 131712,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 132480,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 133248,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 134016,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 134784,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 135168,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 135216,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 136320,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 137088,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 137856,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 139392,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 140160,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 140928,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 141696,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 142464,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 143232,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 144000,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 144768,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 145536,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 146304,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 147072,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 147456,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 147840,
        duration_tick: 384,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 148224,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 148416,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 148608,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 148800,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 148992,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 149184,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 149376,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 149568,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 149760,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 149952,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 150144,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 150336,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 150528,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 150720,
        duration_tick: 192,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 150912,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 150960,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 172416,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 172464,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 172656,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 172704,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 175488,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 175536,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 176256,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 177024,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 177792,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 178560,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 178608,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 178800,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 178848,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 179328,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 180096,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 180864,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 181632,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 182400,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 183168,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 183936,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 184704,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 184752,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 184944,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 184992,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 185472,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 186240,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 187008,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 187776,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 188544,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 189312,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 190080,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 190848,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 190896,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 191088,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 191136,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 191616,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 192384,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 193152,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 193920,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 194688,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 195456,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 196224,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 196992,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 197040,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 197232,
        duration_tick: 48,
        n_midi: 38,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 197280,
        duration_tick: 192,
        n_midi: 38,
        velocity: 37,
    },
];

pub fn snare_drum_score() -> Vec<Note<LeadGuitarArticulation>> {
    SCORE
        .iter()
        .map(|event| Note {
            n_midi: event.n_midi,
            duration: ticks_to_duration(event.duration_tick),
            velocity: event.velocity as f32 / 127.0,
            amplitude_multiplier: 0.5,
            expression: None,
            offset: ticks_to_duration(event.start_tick),
            articulation: LeadGuitarArticulation::Sustained,
        })
        .collect()
}

fn ticks_to_duration(ticks: u32) -> Duration {
    let micros = (ticks as u64)
        .saturating_mul(TEMPO_MICROS_PER_QUARTER_NOTE)
        .saturating_add(TICKS_PER_QUARTER_NOTE / 2)
        / TICKS_PER_QUARTER_NOTE;
    Duration::from_micros(micros)
}
