use std::time::Duration;

use crate::instrumentation::{LeadGuitarArticulation, Note};

const TICKS_PER_QUARTER_NOTE: u64 = 384;
const TEMPO_MICROS_PER_QUARTER_NOTE: u64 = 483_870;

#[derive(Clone, Copy)]
struct ScoreEvent {
    start_tick: u32,
    duration_tick: u32,
    n_midi: u8,
    velocity: u8,
}

const SCORE: &[ScoreEvent] = &[
    ScoreEvent {
        start_tick: 151968,
        duration_tick: 96,
        n_midi: 48,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 152160,
        duration_tick: 96,
        n_midi: 48,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 152736,
        duration_tick: 96,
        n_midi: 48,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 153504,
        duration_tick: 96,
        n_midi: 48,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 153696,
        duration_tick: 96,
        n_midi: 48,
        velocity: 31,
    },
    ScoreEvent {
        start_tick: 154752,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155040,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155040,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155040,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155136,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155232,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155232,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155232,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155520,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155520,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155808,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155808,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 155904,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 156288,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 156576,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 156576,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 156576,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 156672,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 156768,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 156768,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 156768,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 157056,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 157056,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 157344,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 157344,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 157440,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 157824,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158112,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158112,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158112,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158208,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158304,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158304,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158304,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158592,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158592,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158880,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158880,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 158976,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 159360,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 159648,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 159648,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 159648,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 159744,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 159840,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 159840,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 159840,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 160128,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 160128,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 160416,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 160416,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 160512,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 160896,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161184,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161184,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161184,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161280,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161376,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161376,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161376,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161664,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161664,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161952,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 161952,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 162048,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 162432,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 162720,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 162720,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 162720,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 162816,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 162912,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 162912,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 162912,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 163200,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 163200,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 163488,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 163488,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 163584,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 163968,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 164256,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 164256,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 164256,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 164352,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 164448,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 164448,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 164448,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 164736,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 164736,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165024,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165024,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165120,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165504,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165792,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165792,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165792,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165888,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165984,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165984,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 165984,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 166272,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 166272,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 166560,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 166560,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 166656,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 167040,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 167328,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 167328,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 167328,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 167424,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 167520,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 167520,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 167520,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 167808,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 167808,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 168096,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 168096,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 168192,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 168576,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 168864,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 168864,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 168864,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 168960,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 169056,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 169056,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 169056,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 169344,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 169344,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 169632,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 169632,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 169728,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 170112,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 170400,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 170400,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 170400,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 170496,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 170592,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 170592,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 170592,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 170880,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 170880,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 171168,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 171168,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 171264,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 171648,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 171936,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 171936,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 171936,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 172032,
        duration_tick: 96,
        n_midi: 43,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 172128,
        duration_tick: 96,
        n_midi: 48,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 172128,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
    ScoreEvent {
        start_tick: 172128,
        duration_tick: 96,
        n_midi: 62,
        velocity: 37,
    },
];

pub fn toms_snare_score() -> Vec<Note<LeadGuitarArticulation>> {
    SCORE
        .iter()
        .map(|event| Note {
            n_midi: event.n_midi,
            duration: ticks_to_duration(event.duration_tick),
            velocity: event.velocity as f32 / 127.0,
            expression: None,
            offset: ticks_to_duration(event.start_tick),
            articulation: LeadGuitarArticulation::Sustained,
        })
        .collect()
}

fn ticks_to_duration(ticks: u32) -> Duration {
    let micros = (ticks as u64)
        .saturating_mul(TEMPO_MICROS_PER_QUARTER_NOTE)
        .saturating_add(TICKS_PER_QUARTER_NOTE / 2)
        / TICKS_PER_QUARTER_NOTE;
    Duration::from_micros(micros)
}
