use super::{collect_score_from_sections, GridNote, Kind, Position, ScheduledNote};
use crate::instrumentation::ElectricGuitarArticulation;

const INTRO: &[GridNote] = &[];

const VERSE1: &[GridNote] = &[];

const CHORUS1: &[GridNote] = &[];

const VERSE2: &[GridNote] = &[];

const CHORUS2: &[GridNote] = &[];

const SOLO1: &[GridNote] = &[];

const VERSE3: &[GridNote] = &[];

const CHORUS3: &[GridNote] = &[];

const BRIDGE1: &[GridNote] = &[];

const SOLO2: &[GridNote] = &[
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 193.04878,
        position: Position {
            bar: 99,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 193.292683,
        position: Position {
            bar: 100,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 194.02439,
        position: Position {
            bar: 100,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 195.0,
        position: Position {
            bar: 100,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 195.243902,
        position: Position {
            bar: 101,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 196.585366,
        position: Position {
            bar: 101,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 196.95122,
        position: Position {
            bar: 101,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 196.95122,
        position: Position {
            bar: 101,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 196.95122,
        position: Position {
            bar: 101,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 197.073171,
        position: Position {
            bar: 102,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 197.195122,
        position: Position {
            bar: 102,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 197.195122,
        position: Position {
            bar: 102,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 197.195122,
        position: Position {
            bar: 102,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 197.560976,
        position: Position {
            bar: 102,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 197.560976,
        position: Position {
            bar: 102,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 197.926829,
        position: Position {
            bar: 102,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 197.926829,
        position: Position {
            bar: 102,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
];

const BRIDGE2: &[GridNote] = &[
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 198.04878,
        position: Position {
            bar: 102,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 198.536585,
        position: Position {
            bar: 102,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 198.902439,
        position: Position {
            bar: 102,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 198.902439,
        position: Position {
            bar: 102,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 198.902439,
        position: Position {
            bar: 102,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 199.02439,
        position: Position {
            bar: 103,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 199.146341,
        position: Position {
            bar: 103,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 199.146341,
        position: Position {
            bar: 103,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 199.146341,
        position: Position {
            bar: 103,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 199.512195,
        position: Position {
            bar: 103,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 199.512195,
        position: Position {
            bar: 103,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 199.878049,
        position: Position {
            bar: 103,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 199.878049,
        position: Position {
            bar: 103,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 200.0,
        position: Position {
            bar: 103,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 200.487805,
        position: Position {
            bar: 103,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 200.853659,
        position: Position {
            bar: 103,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 200.853659,
        position: Position {
            bar: 103,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 200.853659,
        position: Position {
            bar: 103,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 200.97561,
        position: Position {
            bar: 104,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 201.097561,
        position: Position {
            bar: 104,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 201.097561,
        position: Position {
            bar: 104,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 201.097561,
        position: Position {
            bar: 104,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 201.463415,
        position: Position {
            bar: 104,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 201.463415,
        position: Position {
            bar: 104,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 201.829268,
        position: Position {
            bar: 104,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 201.829268,
        position: Position {
            bar: 104,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 201.95122,
        position: Position {
            bar: 104,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 202.439024,
        position: Position {
            bar: 104,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 202.804878,
        position: Position {
            bar: 104,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 202.804878,
        position: Position {
            bar: 104,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 202.804878,
        position: Position {
            bar: 104,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 202.926829,
        position: Position {
            bar: 105,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 203.04878,
        position: Position {
            bar: 105,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 203.04878,
        position: Position {
            bar: 105,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 203.04878,
        position: Position {
            bar: 105,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 203.414634,
        position: Position {
            bar: 105,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 203.414634,
        position: Position {
            bar: 105,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 203.780488,
        position: Position {
            bar: 105,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 203.780488,
        position: Position {
            bar: 105,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 203.902439,
        position: Position {
            bar: 105,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 204.390244,
        position: Position {
            bar: 105,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 204.756098,
        position: Position {
            bar: 105,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 204.756098,
        position: Position {
            bar: 105,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 204.756098,
        position: Position {
            bar: 105,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 204.878049,
        position: Position {
            bar: 106,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 205.0,
        position: Position {
            bar: 106,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 205.0,
        position: Position {
            bar: 106,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 205.0,
        position: Position {
            bar: 106,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 205.365854,
        position: Position {
            bar: 106,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 205.365854,
        position: Position {
            bar: 106,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 205.731707,
        position: Position {
            bar: 106,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 205.731707,
        position: Position {
            bar: 106,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 205.853659,
        position: Position {
            bar: 106,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 206.341463,
        position: Position {
            bar: 106,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 206.707317,
        position: Position {
            bar: 106,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 206.707317,
        position: Position {
            bar: 106,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 206.707317,
        position: Position {
            bar: 106,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 206.829268,
        position: Position {
            bar: 107,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 206.95122,
        position: Position {
            bar: 107,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 206.95122,
        position: Position {
            bar: 107,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 206.95122,
        position: Position {
            bar: 107,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 207.317073,
        position: Position {
            bar: 107,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 207.317073,
        position: Position {
            bar: 107,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 207.682927,
        position: Position {
            bar: 107,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 207.682927,
        position: Position {
            bar: 107,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 207.804878,
        position: Position {
            bar: 107,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 208.292683,
        position: Position {
            bar: 107,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 208.658537,
        position: Position {
            bar: 107,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 208.658537,
        position: Position {
            bar: 107,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 208.658537,
        position: Position {
            bar: 107,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 208.780488,
        position: Position {
            bar: 108,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 208.902439,
        position: Position {
            bar: 108,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 208.902439,
        position: Position {
            bar: 108,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 208.902439,
        position: Position {
            bar: 108,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 209.268293,
        position: Position {
            bar: 108,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 209.268293,
        position: Position {
            bar: 108,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 209.634146,
        position: Position {
            bar: 108,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 209.634146,
        position: Position {
            bar: 108,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 209.756098,
        position: Position {
            bar: 108,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 210.243902,
        position: Position {
            bar: 108,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 210.609756,
        position: Position {
            bar: 108,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 210.609756,
        position: Position {
            bar: 108,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 210.609756,
        position: Position {
            bar: 108,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 210.731707,
        position: Position {
            bar: 109,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 210.853659,
        position: Position {
            bar: 109,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 210.853659,
        position: Position {
            bar: 109,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 210.853659,
        position: Position {
            bar: 109,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 211.219512,
        position: Position {
            bar: 109,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 211.219512,
        position: Position {
            bar: 109,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 211.585366,
        position: Position {
            bar: 109,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 211.585366,
        position: Position {
            bar: 109,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 211.707317,
        position: Position {
            bar: 109,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 212.195122,
        position: Position {
            bar: 109,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 212.560976,
        position: Position {
            bar: 109,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 212.560976,
        position: Position {
            bar: 109,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 212.560976,
        position: Position {
            bar: 109,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 212.682927,
        position: Position {
            bar: 110,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 212.804878,
        position: Position {
            bar: 110,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 212.804878,
        position: Position {
            bar: 110,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 212.804878,
        position: Position {
            bar: 110,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 213.170732,
        position: Position {
            bar: 110,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 213.170732,
        position: Position {
            bar: 110,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 213.536585,
        position: Position {
            bar: 110,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 213.536585,
        position: Position {
            bar: 110,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 213.658537,
        position: Position {
            bar: 110,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 214.146341,
        position: Position {
            bar: 110,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 214.512195,
        position: Position {
            bar: 110,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 214.512195,
        position: Position {
            bar: 110,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 214.512195,
        position: Position {
            bar: 110,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 214.634146,
        position: Position {
            bar: 111,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 214.756098,
        position: Position {
            bar: 111,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 214.756098,
        position: Position {
            bar: 111,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 214.756098,
        position: Position {
            bar: 111,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 215.121951,
        position: Position {
            bar: 111,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 215.121951,
        position: Position {
            bar: 111,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 215.487805,
        position: Position {
            bar: 111,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 215.487805,
        position: Position {
            bar: 111,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 215.609756,
        position: Position {
            bar: 111,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 216.097561,
        position: Position {
            bar: 111,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 216.463415,
        position: Position {
            bar: 111,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 216.463415,
        position: Position {
            bar: 111,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 216.463415,
        position: Position {
            bar: 111,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 216.585366,
        position: Position {
            bar: 112,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 216.707317,
        position: Position {
            bar: 112,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 216.707317,
        position: Position {
            bar: 112,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 216.707317,
        position: Position {
            bar: 112,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 217.073171,
        position: Position {
            bar: 112,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 217.073171,
        position: Position {
            bar: 112,
            beat: 2,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 217.439024,
        position: Position {
            bar: 112,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 217.439024,
        position: Position {
            bar: 112,
            beat: 2,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 217.560976,
        position: Position {
            bar: 112,
            beat: 3,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 218.04878,
        position: Position {
            bar: 112,
            beat: 4,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 218.414634,
        position: Position {
            bar: 112,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 218.414634,
        position: Position {
            bar: 112,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 218.414634,
        position: Position {
            bar: 112,
            beat: 4,
            beat_offset_num: 3,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 43,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 218.536585,
        position: Position {
            bar: 113,
            beat: 1,
            beat_offset_num: 0,
            beat_offset_den: 1,
        },
    },
    GridNote {
        midi: 48,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 218.658537,
        position: Position {
            bar: 113,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 218.658537,
        position: Position {
            bar: 113,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
    GridNote {
        midi: 62,
        kind: Kind::Sixteenth,
        beats: 0.25,
        d_sec: 0.121951,
        t_sec: 218.658537,
        position: Position {
            bar: 113,
            beat: 1,
            beat_offset_num: 1,
            beat_offset_den: 4,
        },
    },
];

const FINALE: &[GridNote] = &[];

const SECTIONS: [&[GridNote]; 12] = [
    INTRO, VERSE1, CHORUS1, VERSE2, CHORUS2, SOLO1, VERSE3, CHORUS3, BRIDGE1, SOLO2, BRIDGE2,
    FINALE,
];

pub fn toms_snare_score(bpm: f32) -> Vec<ScheduledNote<ElectricGuitarArticulation>> {
    collect_score_from_sections(&SECTIONS, bpm)
}
