[package]
name = "welcome-video"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.14", features = ["tokio", "svg"] }
iced-av1 = { git = "https://github.com/nicksenger/iced-av1.git", branch = "jungle" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tracing = "0.1"

[lints]
workspace = true
