[package]
name = "jungle-test"
version = "0.1.0"
edition = "2021"

[features]
default = []
postgres = []

[dependencies]
jungle_sdk = { package = "jungle-sdk", path = "../jungle-sdk", features = ["server", "pg", "redb", "fusion"] }

[dev-dependencies]
jungle-persist = { path = "../jungle-persist", features = ["postgres"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true, features = ["derive"] }
postcard = { workspace = true, features = ["alloc"] }
redb = "4.1"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-rustls"] }
tempfile = "3"
chrono = "0.4"
testcontainers = "0.23"
testcontainers-modules = { version = "0.11", features = ["postgres"] }

[lints]
workspace = true
