[package]
name = "jungle-local"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
jungle-client = { path = "../jungle-client" }
jungle-server = { path = "../jungle-server", features = ["redb"] }
jungle-types = { path = "../jungle-types" }
thiserror = { workspace = true }
tokio = { version = "1", features = ["sync", "rt"] }
typosaurus = { workspace = true }
uuid = { workspace = true }
chrono = "0.4"

[lints]
workspace = true
