[package]
name = "jungle-client"
version = "0.1.0"
edition = "2021"

[dependencies]
jungle-types = { path = "../jungle-types" }
uuid = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
dyn-clone = { workspace = true }
directories-next = "2"
quinn = { version = "0.11", default-features = false, features = ["runtime-tokio", "rustls-ring"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
thiserror = "1"
tracing = "0.1"
